name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    name: Frontend lint & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Frontend lint
        working-directory: frontend
        run: npm run lint
      - name: Frontend build
        working-directory: frontend
        run: npm run build

  backend:
    name: Backend build
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Backend build (tsc)
        working-directory: backend
        run: npm run build
